kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    # kubeadmConfigPatches:
    # - |-
    #   apiServer:
    #     extraArgs:
    #       oidc-client-id: kubernetes
    #       oidc-issuer-url: http://127.0.0.1:8080/auth/realms/master
    #       oidc-groups-claim: groups
    #       oidc-groups-prefix: 'keycloak:'
  - role: worker
  - role: worker
  # 58a0f35499502165413b75e619e1000cbb9109bf
